services:
    db:
        image: mysql
        container_name: mysql-database-for-ud
        restart: no
        ports:
            - 3300:3306
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: club_yates_db 
            MYSQL_USER: administrator          
            MYSQL_PASSWORD: 123456  
        volumes:
            - ./mysql/data:/var/lib/mysql           
            - ./mysql/config:/etc/mysql/conf.d      